# YAML
name: build-deploy-dev.yml
on:
  push:
    branches:
      - feature/*

jobs:
  checkout:
    runs-on: ubuntu-latest
    environment: dev

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout
        env:
          STEP_NAME: Checkout
        run: |
          echo "::debug::step[checkout]"
          echo "::debug::AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "::debug::AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "::debug::AWS_REGION: $AWS_REGION"

      - name: build
        env:
          STEP_NAME: Build
        run: |
          echo "::debug::Step: $STEP_NAME"
          echo "::debug::AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID"
          echo "::debug::AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "::debug::AWS_REGION: $AWS_REGION"
      - name: Tag
        env:
          STEP_NAME: Build
        run: |
          echo "::debug::Step: $STEP_NAME"
          echo "::debug::AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID"
          echo "::debug::AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "::debug::AWS_REGION: $AWS_REGION"
  deploy-to-dev:
    needs: checkout
    runs-on: ubuntu-latest
    environment: dev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
        - name: setup
          env:
            STEP_NAME: Generate Hash
          run: |
            echo "::debug::step[checkout]"
            echo "::debug::AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
            echo "::debug::AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
            echo "::debug::AWS_REGION: $AWS_REGION"
        - name: build
          env:
            STEP_NAME: Upload Artifact
          run: |
            echo "::debug::Step: $STEP_NAME"
            echo "::debug::AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID"
            echo "::debug::AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
            echo "::debug::AWS_REGION: $AWS_REGION"
        - name: Tag
          env:
            STEP_NAME: Prepare Statement
          run: |
            echo "::debug::Step: $STEP_NAME"
            echo "::debug::AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID"
            echo "::debug::AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
            echo "::debug::AWS_REGION: $AWS_REGION"
