# YAML
name: build-deploy-dev.yml
on:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout
        env:
          STEP_NAME: Checkout
        run: |
          echo "Step: $STEP_NAME"
          echo "AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "AWS_REGION: $AWS_REGION"
      - name: Build
        env:
          STEP_NAME: Build
        run: |
          echo "Step: $STEP_NAME"
          echo "AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "AWS_REGION: $AWS_REGION"
      - name: TAG
        env:
          STEP_NAME: TAG
        run: |
          echo "Step: $STEP_NAME"
          echo "AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "AWS_REGION: $AWS_REGION"
