# YAML
name: build-deploy-dev.yml
on:
  push:
    branches:
      - feature/*

jobs:
  checkout:
    runs-on: ubuntu-latest
    environment: dev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout
        env:
          STEP_NAME: Checkout
        run: |
          if [ -n "${AWS_ACCESS_KEY_ID:-}" ]; then
            echo "AWS_ACCESS_KEY_ID present (length=${#AWS_ACCESS_KEY_ID})"
          else
            echo "AWS_ACCESS_KEY_ID missing"
          fi
    
          echo "::debug::step[checkout]"
          echo "::debug::AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "::debug::AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "::debug::AWS_REGION: $AWS_REGION"

      - name: build
        env:
          STEP_NAME: Build
        run: |
          
          if [ -n "${AWS_ACCESS_KEY_ID:-}" ]; then
            echo "AWS_ACCESS_KEY_ID present (length=${#AWS_ACCESS_KEY_ID})"
          else
            echo "AWS_ACCESS_KEY_ID missing"
          fi

          echo "::debug::Step: $STEP_NAME"
          echo "::debug::AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID"
          echo "::debug::AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "::debug::AWS_REGION: $AWS_REGION"
                - name: TAG
        env:
          STEP_NAME: TAG
        run: |
          
          if [ -n "${AWS_ACCESS_KEY_ID:-}" ]; then
            echo "AWS_ACCESS_KEY_ID present (length=${#AWS_ACCESS_KEY_ID})"
          else
            echo "AWS_ACCESS_KEY_ID missing"
          fi
          echo "::debug::Step: $STEP_NAME"
          echo "::debug::AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID"
          echo "::debug::AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "::debug::AWS_REGION: $AWS_REGION"
          
